### ISSUE TITLE
Allow for callback function to set uncertainty decay

### ISSUE THREAD

**Issue by zass30** [glandfried/TrueSkillThroughTime.py#2]
Let a user specify a manual uncertainty decay function. This could either be run at set intervals in a game's history for all players (for example as a daily job), or else called ad-hoc when querying a given player's ranking, or else called as a callback when parsing new games.
As an example, a basic decay function could be that sigma is multiplied by some factor, like 1.1, for every day a player has not played.

(also posted this issue in the main TTT page https://github.com/glandfried/TrueSkillThroughTime/issues/2  -- feel free to delete this or the other, depending on where this issues is better placed)

**Comment by glandfried** [comment]
We keep talking at https://github.com/glandfried/TrueSkillThroughTime/issues/2
