### ISSUE TITLE
math domain error when getting `history.log_evidence()`

### ISSUE THREAD

**Issue by mrkvicka22** [glandfried/TrueSkillThroughTime.py#3]
at least one `event.evidence` had to have been <= 0 and therefore math.log() gave domain error.

```
def log_evidence(self):
    return sum([math.log(event.evidence) for b in self.batches for event in b.events])
```

**Comment by glandfried** [comment]
Maybe some numerical issue. Could you send me a code that reproduces the error, please? 
Thanks for letting me know!

**Comment by mrkvicka22** [comment]
> Maybe some numerical issue. Could you send me a code that reproduces the error, please? Thanks for letting me know!

Okay, I will try to get a minimal example, otherwise I will have to send the data as it is... 

My assumption is that you either round somewhere or it is very very confident in one outcome and either way the `event.evidence` becomes 0 which obviously breaks the logarithm.

**Comment by glandfried** [comment]
Hi, do you have any news?

**Comment by mrkvicka22** [comment]
Not really. I dont have the data that caused it anymore

**Comment by glandfried** [comment]
[Version V2.0.0 is coming soon](https://github.com/glandfried/TrueSkillThroughTime.py/pull/13#issue-3627591607)
