### ISSUE TITLE
Issues with large multi team compositions: unsupported operand type(s) for +: 'float' and 'datetime.timedelta'

### ISSUE THREAD

**Issue by manhellis** [glandfried/TrueSkillThroughTime.py#4]
Hello

I'm encountering an error when running large compositions of multi team events into the history class.
The following is a view of my data that does work how I expect.
![image](https://user-images.githubusercontent.com/29523807/206835261-2282984d-15d4-4065-a2cb-5a0a307c2656.png)

And this is an example of a view that gives an error.
![image](https://user-images.githubusercontent.com/29523807/206835307-5eb10a12-a036-43a4-8c96-d2f76cabb4b6.png)

I'm struggling to find a solution! Thanks for the help.

This is the error message.
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-100-13e9a1b21181> in <module>

----> 2 h = ttt.History(composition = composition, times = times, priors = prior_dict)
     

~\anaconda3\lib\site-packages\trueskillthroughtime\__init__.py in __init__(self, composition, results, times, priors, mu, sigma, beta, gamma, p_draw)
    515         self.p_draw = p_draw
    516         self.time = len(times)>0
--> 517         self.trueskill(composition,results,times)
    518 
    519     def __repr__(self):

~\anaconda3\lib\site-packages\trueskillthroughtime\__init__.py in trueskill(self, composition, results, times)
    530                 b = Batch([composition[k] for k in o[i:j]],[results[k] for k in o[i:j]], t, self.agents, self.p_draw)
    531             else:
--> 532                 b = Batch([composition[k] for k in o[i:j]],[], t, self.agents, self.p_draw)
    533             self.batches.append(b)
    534             for a in b.skills:

~\anaconda3\lib\site-packages\trueskillthroughtime\__init__.py in __init__(self, composition, results, time, agents, p_draw)
    430         elapsed = dict([ (a,  compute_elapsed(agents[a].last_time, time) ) for a in this_agents ])
    431 
--> 432         self.skills = dict([ (a, Skill(agents[a].receive(elapsed[a]) ,Ninf ,Ninf , elapsed[a])) for a in this_agents  ])
    433         self.events = [Event([Team([Item(composition[e][t][a], Ninf) for a in range(len(composition[e][t])) ], results[e][t] if len(results) > 0 else len(composition[e]) - t - 1  ) for t in range(len(composition[e])) ],0.0) for e in range(len(composition) )]
    434         self.time = time

~\anaconda3\lib\site-packages\trueskillthroughtime\__init__.py in <listcomp>(.0)
    430         elapsed = dict([ (a,  compute_elapsed(agents[a].last_time, time) ) for a in this_agents ])
    431 
--> 432         self.skills = dict([ (a, Skill(agents[a].receive(elapsed[a]) ,Ninf ,Ninf , elapsed[a])) for a in this_agents  ])
    433         self.events = [Event([Team([Item(composition[e][t][a], Ninf) for a in range(len(composition[e][t])) ], results[e][t] if len(results) > 0 else len(composition[e]) - t - 1  ) for t in range(len(composition[e])) ],0.0) for e in range(len(composition) )]
    434         self.time = time

~\anaconda3\lib\site-packages\trueskillthroughtime\__init__.py in receive(self, elapsed)
    380     def receive(self, elapsed):
    381         if self.message != Ninf:
--> 382             res = self.message.forget(self.player.gamma, elapsed)
    383         else:
    384             res = self.player.prior

~\anaconda3\lib\site-packages\trueskillthroughtime\__init__.py in forget(self, gamma, t)
    185         return Gaussian(mu, sigma)
    186     def forget(self,gamma,t):
--> 187         return Gaussian(self.mu, math.sqrt(self.sigma**2 + t*gamma**2))
    188     def delta(self, M):
    189         return abs(self.mu - M.mu) , abs(self.sigma - M.sigma)

TypeError: unsupported operand type(s) for +: 'float' and 'datetime.timedelta'`

**Comment by glandfried** [comment]
Hi!

I think you are sending "datetime" into the variable `times` when you are initializing the History class.

```ttt.History(composition = composition, times = times, priors = prior_dict)```

The variable `times`, if not empty, must be an array of numbers, floats or integers.  

Let me know if you have any other question.

**Comment by glandfried** [comment]
Hi, do you have any news?

**Comment by manhellis** [comment]
Hi, sorry for the late response.

Your answer was helpful, I am figuring out how to pass different compositions through the h class. I have an array of float times currently but am getting div0 errors.

I appreciate your help, your package has been really helpful and I've been learning a lot!

![image](https://github.com/glandfried/TrueSkillThroughTime.py/assets/29523807/29721084-4a25-4522-a9ae-c35339e619bb)
![image](https://github.com/glandfried/TrueSkillThroughTime.py/assets/29523807/d40b5e83-eb39-497b-a0e8-25f556abd2d7)

**Comment by glandfried** [comment]
Hi, 

Do you have an example to replicate the error?

**Comment by glandfried** [comment]
[Version V2.0.0 is coming soon](https://github.com/glandfried/TrueSkillThroughTime.py/pull/13#issue-3627591607)
