### ISSUE TITLE
Does it support games with higher number of participants per round?

### ISSUE THREAD

**Issue by tirksam** [glandfried/TrueSkillThroughTime.py#7]
With standard Trueskill implementation I can have rounds of for example 16 players who have ranking from 1-16 per round. 

Looking at the examples Trueskill Through Time has examples of either 1vs1 games or 2vs2 games. Is there a way to implement it for larger games as in above example?

**Comment by glandfried** [comment]
You can use any team configuration you such as 1vs1vs1...vs1 or 2vs3vs1vs5.

**Comment by tirksam** [comment]
Thank you for the quick reply. Does this address the internal ranking inside the match vs other players? If it is versus everyone game. 

For example how can I rank player who was seventh in the match as he would have lost to first six and won the last 9 players.

**Comment by glandfried** [comment]
[Version V2.0.0 is coming soon](https://github.com/glandfried/TrueSkillThroughTime.py/pull/13#issue-3627591607)
