### ISSUE TITLE
Handling ZeroDivisionError in the v_w Function

### ISSUE THREAD

**Issue by apiss2** [glandfried/TrueSkillThroughTime.py#9]
Handling ZeroDivisionError in the v_w Function

It is possible that cdf(-_alpha, 0, 1) or (cdf(_beta, 0, 1) - cdf(_alpha, 0, 1)) could become zero. What values of v or w are expected when a division by zero occurs?

Additionally, due to floating-point calculation errors, w might exceed 1. In such cases, the math.sqrt(1-w) within the trunc function might throw an error. Is it necessary to implement special handling for cases where w exceeds 1?

**Comment by glandfried** [comment]
[Version V2.0.0 is coming soon](https://github.com/glandfried/TrueSkillThroughTime.py/pull/13#issue-3627591607)
